name: Publish Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.17.0
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
        working-directory: plugin
      - name: publish
        run: pnpm publish
        working-directory: plugin
